#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-gossip
Version  : 1.8
Release  : 1
URL      : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.jar
Source0  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.jar
Source1  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-bootstrap/1.8/gossip-bootstrap-1.8.jar
Source2  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-bootstrap/1.8/gossip-bootstrap-1.8.pom
Source3  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.jar
Source4  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.pom
Source5  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-slf4j/1.8/gossip-slf4j-1.8.jar
Source6  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip-slf4j/1.8/gossip-slf4j-1.8.pom
Source7  : https://repo1.maven.org/maven2/org/sonatype/gossip/gossip/1.8/gossip-1.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-gossip-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-gossip package.
Group: Data

%description data
data components for the mvn-gossip package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-bootstrap/1.8
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-bootstrap/1.8/gossip-bootstrap-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-bootstrap/1.8
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-bootstrap/1.8/gossip-bootstrap-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-slf4j/1.8
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-slf4j/1.8/gossip-slf4j-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-slf4j/1.8
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-slf4j/1.8/gossip-slf4j-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip/1.8
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/gossip/gossip/1.8/gossip-1.8.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-bootstrap/1.8/gossip-bootstrap-1.8.jar
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-bootstrap/1.8/gossip-bootstrap-1.8.pom
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.jar
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-core/1.8/gossip-core-1.8.pom
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-slf4j/1.8/gossip-slf4j-1.8.jar
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip-slf4j/1.8/gossip-slf4j-1.8.pom
/usr/share/java/.m2/repository/org/sonatype/gossip/gossip/1.8/gossip-1.8.pom
